### ISSUE TITLE
GetVisualStudioVersion failing

### ISSUE THREAD

**Issue by ctaggart** [mono/embeddinator-4000#1]
I'm trying this out and this is the first issue I've run into. It doesn't seem to detect my Visual Studio install.
```
PS C:\Users\cameron\fs\embeddinator-4000\tests\Basic> MonoEmbeddinator4000 --compile --dll bin\Release\ClassLibrary1.dll
Parsing assemblies...
    Parsed 'ClassLibrary1.dll'
Processing assemblies...
Generating binding code...
    Generated: ClassLibrary1.h
    Generated: ClassLibrary1.c
    Generated: glib.c
    Generated: glib.h
    Generated: main.c
    Generated: mono_embeddinator.c
    Generated: mono_embeddinator.h
Compiling binding code...

Unhandled Exception: System.Exception: Unknown Visual Studio version
   at CppSharp.MSVCToolchain.GetVisualStudioVersion(VisualStudioVersion version) in C:\Users\cameron\fs\embeddinator-4000\CppSharp\src\Core\Toolchains\MSVCToolchain.cs:line 115
   at CppSharp.MSVCToolchain.<>c__DisplayClass5_0.<GetVSToolchain>b__0(ToolchainVersion version) in C:\Users\cameron\fs\embeddinator-4000\CppSharp\src\Core\Toolchains\MSVCToolchain.cs:line 130
   at System.Collections.Generic.List`1.Find(Predicate`1 match)
   at CppSharp.MSVCToolchain.GetVSToolchain(VisualStudioVersion vsVersion) in C:\Users\cameron\fs\embeddinator-4000\CppSharp\src\Core\Toolchains\MSVCToolchain.cs:line 127
   at CppSharp.MSVCToolchain.GetSystemIncludes(VisualStudioVersion vsVersion) in C:\Users\cameron\fs\embeddinator-4000\CppSharp\src\Core\Toolchains\MSVCToolchain.cs:line 178
   at MonoManagedToNative.Driver.CompileCode() in C:\Users\cameron\fs\embeddinator-4000\binder\Driver.cs:line 244
   at MonoManagedToNative.Driver.Run() in C:\Users\cameron\fs\embeddinator-4000\binder\Driver.cs:line 324
   at MonoManagedToNative.Binder.Main(String[] args) in C:\Users\cameron\fs\embeddinator-4000\binder\Binder.cs:line 102
```

Looks to be blowing up here:
https://github.com/mono/CppSharp/blob/master/src/Core/Toolchains/MSVCToolchain.cs#L115

Vanilla update 3:
![image](https://cloud.githubusercontent.com/assets/80104/20082477/f6a03096-a50a-11e6-8f14-e6681874c52b.png)

**Comment by ctaggart** [comment]
This doesn't work with Visual Studio 2010 Shell installed. That was installed with SSMS 2014. I've since upgraded to SSMS 2016 an no longer need it. I've uninstalled it and now am onto the next dependency.
