### ISSUE TITLE
[java] LINQ crashes Android

### ISSUE THREAD

**Issue by mattleibow** [mono/Embeddinator-4000#408]
I had a simple LINQ `new [] { 1, 2, 3 }.FirstOrDefault()`, and this crashes:

```
Caused by: mono.embeddinator.RuntimeException
    at mono.embeddinator.Runtime$1.invoke(Runtime.java:119)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:520)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:551)
    at com.sun.jna.Native.invokePointer(Native Method)
    at com.sun.jna.Function.invokePointer(Function.java:490)
    at com.sun.jna.Function.invoke(Function.java:434)
    at com.sun.jna.Function.invoke(Function.java:354)
    at com.sun.jna.Library$Handler.invoke(Library.java:244)
    at java.lang.reflect.Proxy.invoke(Proxy.java:813)
    at $Proxy1.ManagedLibrary_Calculator_new(Unknown Source)
    at managedlibrary_dll.managedlibrary.Calculator.<init>(Calculator.java:20)
    at com.example.matthew.myapplication.MainActivity.onCreate(MainActivity.java:27)
    at android.app.Activity.performCreate(Activity.java:6664)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
    at android.app.ActivityThread.-wrap12(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.app.ActivityThread.main(ActivityThread.java:6077) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
```

If I do a `foreach`, it works. This code also works fine on iOS.

**Comment by jonathanpeppers** [comment]
@mattleibow can you run:
```
zipinfo yourassemblyname.aar
```

I wanted to see if `System.Core.dll` is included.

**Comment by tritao** [comment]
This should work now, please re-open if still an issue.
