### ISSUE TITLE
[android] dlopen failed: cannot locate symbol "monodroid_embedded_assemblies_set_assemblies_prefix"

### ISSUE THREAD

**Issue by mattleibow** [mono/Embeddinator-4000#436]
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.matthew.myapplication, PID: 2400
                  java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "monodroid_embedded_assemblies_set_assemblies_prefix" referenced by "/data/app/com.example.matthew.myapplication-1/lib/x86/libManagedAndroidLibrary.so"...
                      at java.lang.Runtime.loadLibrary0(Runtime.java:977)
                      at java.lang.System.loadLibrary(System.java:1530)
                      at mono.embeddinator.AndroidImpl.initialize(AndroidImpl.java:26)
                      at mono.embeddinator.Runtime.initialize(Runtime.java:125)
                      at mono.embeddinator.Runtime.loadLibrary(Runtime.java:151)
                      at managedandroidlibrary.Native_ManagedAndroidLibrary.<clinit>(Native_ManagedAndroidLibrary.java:17)
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.Class.forName(Class.java:400)
                      at java.lang.Class.forName(Class.java:326)
                      at mono.embeddinator.AndroidRuntimeProvider.attachInfo(AndroidRuntimeProvider.java:22)
                      at android.app.ActivityThread.installProvider(ActivityThread.java:5811)
                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:5403)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5342)
                      at android.app.ActivityThread.-wrap2(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by mattleibow** [comment]
I am still testing my sample repo: https://github.com/mattleibow/EmbeddedManagedDemo

The compiler now correctly generates the java files and builds the .so and .aar files. I created an Android Studio app, and pulled that .aar in. The code seems to compile, but at runtime that symbol is missing.

I did a nm on the .so and found that that symbol was `U`:

```
> nm libManagedAndroidLibrary.so | grep monodroid_embedded_assemblies_set_assemblies_prefix
         U monodroid_embedded_assemblies_set_assemblies_prefix
```

**Comment by mattleibow** [comment]
This appears in the `mono_embeddinator.c` file:

```c
MONO_API int monodroid_embedded_assemblies_set_assemblies_prefix (const char *prefix);

JNIEXPORT void JNICALL
Java_mono_embeddinator_AndroidImpl_setAssemblyPrefix()
{
    monodroid_embedded_assemblies_set_assemblies_prefix("assets/assemblies/");
}
```

I am thinking something is not being linked?

**Comment by jonathanpeppers** [comment]
I had to make a change to Xamarin.Android for embeddinator.

Did you run:
```
./build.sh -t Generate-Android
```

This will download a version of Xamarin.Android in `external/Xamarin.Android` to use instead of the system one. It mentions it on the updated [guide](https://mono.github.io/Embeddinator-4000/getting-started-java-android.html), but it is a temporary thing.

Maybe I need to make it fail right now (if it is using your system XA) until the next release of Xamarin.Android.

**Comment by tritao** [comment]
Closing since this is not an issue if you follow instructions by @jonathanpeppers and use the necessary dependencies.
