### ISSUE TITLE
Generating on Non-Xamarin Projects

### ISSUE THREAD

**Issue by nolanblew** [mono/Embeddinator-4000#515]
Is there a specific requirement for the Embeddinator to generatore on only Xamarin projects? It seems to crash every time when processing a library that was not Xamarin. I get:
```
Unhandled Exception: System.IO.FileNotFoundException: System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
   at IKVM.Reflection.Universe.Load(String refname, Module requestingModule, Boolean throwOnError)
   at IKVM.Reflection.Reader.ModuleReader.ResolveAssemblyRefImpl(Record& rec)
   at IKVM.Reflection.Reader.ModuleReader.ResolveAssemblyRef(Int32 index)
   at IKVM.Reflection.Reader.ModuleReader.ResolveType(Int32 metadataToken, IGenericContext context)
   at IKVM.Reflection.Reader.TypeDefImpl.get_BaseType()
   at IKVM.Reflection.Type.get_IsEnum()
   at Embeddinator.Generators.ASTGenerator.Visit(TypeInfo typeInfo)
   at Embeddinator.Generators.ASTGenerator.Visit(Assembly assembly)
   at Embeddinator.Driver.Process()
   at Embeddinator.Driver.Run()
   at Embeddinator.CLI.Main(String[] args)`
```

With the version of `System.Runtime` being different depending on the target type. This occurs when attempting to gen a .NET Standard dll (1.2, 1.4, 1.6, and 2.0) as well as .NET Core (1.0 and 1.1) and .NET 4.5 portable library.

The only success I have is when I create a Xamarin library and compile. Is this a requirement for the Embeddinator to work?

**Comment by tritao** [comment]
Hey Nolan,

This seems like a bug, can you attach an example of such an assembly? I'll take a look.

**Comment by nolanblew** [comment]
Sure. Here is a simple weather API that I created using .NET Standard 1.4.

[MyWeatherApi.zip](https://github.com/mono/Embeddinator-4000/files/1322838/MyWeatherApi.zip)

**Comment by tritao** [comment]
Related to .NET Standard, we're already tracking on another issue.

**Comment by Shayon** [comment]
@tritao Can you link to this other issue that is related to .NET Standard 1.4 support? Or is it this issue? https://github.com/mono/Embeddinator-4000/issues/518 Is Embeddinator only planning on supporting Standard 2.0?

**Comment by tritao** [comment]
Yes that is the issue, we will support all .NET Standard versions.
