### ISSUE TITLE
Can't create aar file with Xamarin Forms

### ISSUE THREAD

**Issue by vitalim4** [mono/Embeddinator-4000#669]
I 've created cross platform application. I am trying to create an aar file for Android project that includes .Net Class Libraries. After trying to Build, getting this Error:

My command:
set OUTPUT="$(SolutionDir)output"
if exist %OUTPUT% rmdir /S /Q %OUTPUT%
"$(SolutionDir)packages\Embeddinator-4000.0.4.0\tools\Embeddinator-4000.exe" "$(TargetPath)" --gen=Java --platform=Android --outdir=%OUTPUT% -c

 Unhandled Exception: System.IO.FileNotFoundException: Xamarin.Forms.Platform.Android, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null
    at IKVM.Reflection.Universe.Load(String refname, Module requestingModule, Boolean throwOnError)
     at IKVM.Reflection.Reader.ModuleReader.ResolveAssemblyRefImpl(Record& rec)
     at IKVM.Reflection.Reader.ModuleReader.ResolveAssemblyRef(Int32 index)
     at IKVM.Reflection.Reader.ModuleReader.ResolveType(Int32 metadataToken, IGenericContext context)
     at IKVM.Reflection.Reader.TypeDefImpl.get_BaseType()
     at IKVM.Reflection.Type.get_IsEnum()
     at Embeddinator.Generators.ASTGenerator.Visit(TypeInfo typeInfo)
     at Embeddinator.Generators.ASTGenerator.Visit(Assembly assembly)
     at Embeddinator.Driver.Process()
     at Embeddinator.Driver.Run()
     at Embeddinator.CLI.Main(String[] args)

**Comment by charmosz** [comment]
Same here. Did you find a solution ?

**Comment by vitalim4** [comment]
As I understood, You can't work with cross- platform and Embeddinator. You need to create project for each platform separately.

**Comment by charmosz** [comment]
ok :(. Did you find another solution to embed a crossplatform Xamarin forms app into a Java or ObjC app ? Or did you split your project in 2 specific platform projects ?

**Comment by vitalim4** [comment]
I've splited my projects. Ios and Android
