### ISSUE TITLE
Cannot find Mono SDK, it needs to be installed on the system.

### ISSUE THREAD

**Issue by Nyconing** [mono/Embeddinator-4000#676]
I have Winbows10 Pro 64bit, VS2017, Mono2.12.0.226(x64)
, AS3.0 and Java Environment installed,
But I have a exception when try to run Embeddinator-4000: Cannot find Mono SDK, it needs to be installed on the system.

I have checked the Source code on ManagedToolchain.FindMonoPath();
But I still cant find out what is the problem.
-I have registry 
```
\HKEY_LOCAL_MACHINE\SOFTWARE\Mono
```
And Valid value for SdkInstallRoot.
```
C:\Program Files\Mono\
```
This path is exist.
### Expected Behavior
It should be fine.
### Actual Behavior
Exception occur.
### Environment
Windows10 Pro 64bit, tried with Administrator and ran on Administrator account.

```
Embeddinator-4000.exe "C:\Projs\ProjectVanSales\ProjectVanSales\bin\Release\ProjectVanSales.dll" --gen=Java --platform=Android --outdir="C:\Projs\ProjectVanSales\output" -c
```

### Build Logs
```
Parsing assemblies...
    Parsed 'ProjectVanSales.dll'
Processing assemblies...
Generating binding code...
    Generated: ProjectVanSales.h
    Generated: ProjectVanSales.c
    Generated: Mono.Android.h
    Generated: Mono.Android.c
    Generated: Java.Interop.h
    Generated: Java.Interop.c
    Generated: mscorlib.h
    Generated: mscorlib.c
    Generated: Xamarin.Android.Support.v7.RecyclerView.h
    Generated: Xamarin.Android.Support.v7.RecyclerView.c
    Generated: Xamarin.Android.Support.Fragment.h
    Generated: Xamarin.Android.Support.Fragment.c
    Generated: Xamarin.Android.Arch.Lifecycle.Common.h
    Generated: Xamarin.Android.Arch.Lifecycle.Common.c
    Generated: Realm.h
    Generated: Realm.c
    Generated: System.h
    Generated: System.c
    Generated: Xamarin.Android.Support.v7.AppCompat.h
    Generated: Xamarin.Android.Support.v7.AppCompat.c
    Generated: Xamarin.Android.Support.Compat.h
    Generated: Xamarin.Android.Support.Compat.c
    Generated: Xamarin.Android.Support.Core.Utils.h
    Generated: Xamarin.Android.Support.Core.Utils.c
    Generated: Xamarin.Android.Support.Core.UI.h
    Generated: Xamarin.Android.Support.Core.UI.c
    Generated: Xamarin.Android.Support.v7.CardView.h
    Generated: Xamarin.Android.Support.v7.CardView.c
    Generated: c-support.c
    Generated: c-support.h
    Generated: embeddinator.h
    Generated: glib.c
    Generated: glib.h
    Generated: mono-support.c
    Generated: mono-support.h
    Generated: mono_embeddinator.c
    Generated: mono_embeddinator.h
Compiling binding code...

Unhandled Exception: System.Exception: Cannot find Mono SDK, it needs to be installed on the system.
   at Embeddinator.Driver.<>c.<.cctor>b__54_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Embeddinator.Driver.CompileNDK(IEnumerable`1 files)
   at Embeddinator.Driver.CompileNativeCode(IEnumerable`1 files)
   at Embeddinator.Driver.CompileCode()
   at Embeddinator.Driver.Run()
   at Embeddinator.CLI.Main(String[] args)
```

**Comment by jcapellman** [comment]
I had to install the 32bit Mono -> http://www.mono-project.com/download/stable/ ran into the same issue.

**Comment by lkhore** [comment]
Any update on this

**Comment by jcapellman** [comment]
I assume most have moved onto DNNE as a replacement for this project - not to mention some of the new capabilities in .NET 6 + CoreRT's future to create native binaries.
