### ISSUE TITLE
.NET Core 2.1 App -> C Windows Output

### ISSUE THREAD

**Issue by jcapellman** [mono/Embeddinator-4000#697]
### Steps to Reproduce

Real simple .NET Core 2.1 App (VS 2017 15.9 Preview 1.0):

    namespace HostingTest
    {
        public class TestClass
        {
            public string DoWork(string test)
            {
                return test.ToUpper();
            }
        }
    }

Run:
`Embeddinator-4000.exe --gen=c --platform=windows --compile .\HostingTest.dll --static --vs=2017 --shared --verbose`

Output:
`
    Unhandled Exception: System.IO.FileNotFoundException: System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
   at IKVM.Reflection.Universe.Load(String refname, Module requestingModule, Boolean throwOnError)
   at IKVM.Reflection.Reader.ModuleReader.ResolveAssemblyRefImpl(Record& rec)
   at IKVM.Reflection.Reader.ModuleReader.ResolveAssemblyRef(Int32 index)
   at IKVM.Reflection.Reader.ModuleReader.ResolveType(Int32 metadataToken, IGenericContext context)
   at IKVM.Reflection.Reader.TypeDefImpl.get_BaseType()
   at IKVM.Reflection.Type.get_IsEnum()
   at Embeddinator.Generators.ASTGenerator.Visit(TypeInfo typeInfo)
   at Embeddinator.Generators.ASTGenerator.Visit(Assembly assembly)
   at Embeddinator.Driver.Process()
   at Embeddinator.Driver.Run()
   at Embeddinator.CLI.Main(String[] args)
`
A work around to get around this was to copy the System.Runtime.dll from the C:\Program Files (x86)\Mono\lib\mono\xbuild-frameworks\.NETPortable\v4.6 path to my publish folder of the dummy 
net core app.

Now it compiles fine:
PS C:\Users\jcapellman\Source\Repos\HostingTest\bin\Debug\netcoreapp2.1\publish> C:\Users\jcapellman\Source\Repos\packages\embeddinator-4000\0.4.0\tools\Embeddinator-4000.exe --gen=c --platform=windows --compile .\HostingTest.dll --static --vs=2017 --shared --verbose
Parsing assemblies...
    Parsed 'HostingTest.dll'
Processing assemblies...
    Pass 'Embeddinator.Passes.CheckReservedKeywords'
    Pass 'Embeddinator.Passes.GenerateObjectTypesPass'
    Pass 'Embeddinator.Passes.GenerateArrayTypes'
    Pass 'CppSharp.Passes.CheckIgnoredDeclsPass'
    Pass 'Embeddinator.Passes.FieldToGetterSetterPropertyPass'
    Pass 'Embeddinator.Passes.CheckDeclarations'
    Pass 'Embeddinator.Passes.FixMethodParametersPass'
    Pass 'Embeddinator.Passes.CheckReservedKeywords'
Generating binding code...
    Generated: HostingTest.h
    Generated: HostingTest.c
    Generated: c-support.c
    Generated: c-support.h
    Generated: embeddinator.h
    Generated: glib.c
    Generated: glib.h
    Generated: mono-support.c
    Generated: mono-support.h
    Generated: mono_embeddinator.c
    Generated: mono_embeddinator.h
Compiling binding code...
    VS path C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\Common7\IDE
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0
    Invoking: C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\Common7\IDE\..\..\VC\Tools\MSVC\14.15.26726\bin\Hostx86\x86\cl.exe /nologo -DMONO_EMBEDDINATOR_DLL_EXPORT -I"C:\Program Files (x86)\Mono\\include\mono-2.0" "C:\Users\jcapellman\Source\Repos\HostingTest\bin\Debug\netcoreapp2.1\publish\HostingTest.c" "C:\Users\jcapellman\Source\Repos\HostingTest\bin\Debug\netcoreapp2.1\publish\c-support.c" "C:\Users\jcapellman\Source\Repos\HostingTest\bin\Debug\netcoreapp2.1\publish\glib.c" "C:\Users\jcapellman\Source\Repos\HostingTest\bin\Debug\netcoreapp2.1\publish\mono-support.c" "C:\Users\jcapellman\Source\Repos\HostingTest\bin\Debug\netcoreapp2.1\publish\mono_embeddinator.c" "C:\Program Files (x86)\Mono\lib\mono-2.0-sgen.lib" /LD /FeC:\Users\jcapellman\Source\Repos\HostingTest\bin\Debug\netcoreapp2.1\publish\HostingTest
        HostingTest.c
c-support.c
glib.c
mono-support.c
mono_embeddinator.c
Generating Code...
   Creating library C:\Users\jcapellman\Source\Repos\HostingTest\bin\Debug\netcoreapp2.1\publish\HostingTest.lib and object C:\Users\jcapellman\Source\Repos\HostingTest\bin\Debug\netcoreapp2.1\publish\HostingTest.exp

**Comment by mandel-macaque** [comment]
@jcapellman again, thanks for a great issue being reported. As with the other issues, I'm labelling this to bring peoples attention.
