### ISSUE TITLE
Parameter "unevaluatedValue" cannot be null.

### ISSUE THREAD

**Issue by Talgrin** [mono/Embeddinator-4000#712]
I've been trying to follow the documentation (https://docs.microsoft.com/en-us/xamarin/tools/dotnet-embedding/get-started/java/android) with a test project, but keep running into the same issue.

When I run Embeddinator-4000 on my hello-from-csharp.dll, it fails here:

--------------------
Generating binding code...
    Generated: hello_from_csharp\classlibrary1\Class1.java
    Generated: hello_from_csharp\classlibrary1\Resource.java
    Generated: hello_from_csharp\classlibrary1\Animation.java
    Generated: hello_from_csharp\classlibrary1\Attribute.java
    Generated: hello_from_csharp\classlibrary1\Boolean.java
    Generated: hello_from_csharp\classlibrary1\Color.java
    Generated: hello_from_csharp\classlibrary1\Dimension.java
    Generated: hello_from_csharp\classlibrary1\Drawable.java
    Generated: hello_from_csharp\classlibrary1\Id.java
    Generated: hello_from_csharp\classlibrary1\Integer.java
    Generated: hello_from_csharp\classlibrary1\Layout.java
    Generated: hello_from_csharp\classlibrary1\String.java
    Generated: hello_from_csharp\classlibrary1\Style.java
    Generated: hello_from_csharp\classlibrary1\Styleable.java
    Generated: hello_from_csharp\Native_hello_from_csharp.java
    Generated: mscorlib\system\IDisposableImpl.java
    Generated: mscorlib\system\IDisposable.java
    Generated: mscorlib\Native_mscorlib.java
    Generating Java stubs...

Unhandled Exception: System.ArgumentNullException: Parameter "unevaluatedValue" cannot be null.
   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowArgumentNull(Object parameter, String parameterName, String resourceName)
   at Microsoft.Build.Construction.ProjectTaskElement.SetParameter(String name, String unevaluatedValue)
   at Embeddinator.XamarinAndroidBuild.GenerateJavaStubsProject(List`1 assemblies, String outputDirectory)
   at Embeddinator.Driver.WriteFiles()
   at Embeddinator.Driver.Run()
   at Embeddinator.CLI.Main(String[] args)

-------------------

I've also attempted to follow a video example (https://www.youtube.com/watch?v=ZVcrXUpCNpI), with the same results: 

----------------

Generating binding code...
    Generated: fingerpaint\fingerpaint\Resource.java
    Generated: fingerpaint\fingerpaint\Array.java
    Generated: fingerpaint\fingerpaint\Attribute.java
    Generated: fingerpaint\fingerpaint\Drawable.java
    Generated: fingerpaint\fingerpaint\Id.java
    Generated: fingerpaint\fingerpaint\Layout.java
    Generated: fingerpaint\fingerpaint\String.java
    Generated: fingerpaint\Native_FingerPaint.java
    Generated: mscorlib\system\IDisposableImpl.java
    Generated: mscorlib\system\IDisposable.java
    Generated: mscorlib\Native_mscorlib.java
    Generating Java stubs...

Unhandled Exception: System.ArgumentNullException: Parameter "unevaluatedValue" cannot be null.
   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowArgumentNull(Object parameter, String parameterName, String resourceName)
   at Microsoft.Build.Construction.ProjectTaskElement.SetParameter(String name, String unevaluatedValue)
   at Embeddinator.XamarinAndroidBuild.GenerateJavaStubsProject(List`1 assemblies, String outputDirectory)
   at Embeddinator.Driver.WriteFiles()
   at Embeddinator.Driver.Run()
   at Embeddinator.CLI.Main(String[] args)

-------------------
I'm at a loss as to what is going wrong. Could you offer any insight? 

It feels like there is something incredibly obvious I'm missing. Like I missed a step somewhere?

**Comment by andre-g-it** [comment]
Same issue for me. And I fall into issue #663 if I run Embeddinator-4000 adding the flag -c

**Comment by Footmau** [comment]
Try to run the command in verbose mode with parameter -v.

**Comment by lindexi** [comment]
Key HKCU\SOFTWARE\Novell\Mono for Android\AndroidSdkDirectory not found
