### ISSUE TITLE
Update VS2017 to v15.9.x breaks embeddinator with "Failed to resolve System.String[]"

### ISSUE THREAD

**Issue by nisewond** [mono/Embeddinator-4000#713]
### Steps to Reproduce

1. Include calls to  System.String Split(), Trim(), TrimeEnd(), TrimStart() which pass in a Char instead of Char[].  
Example: 
String s = "a,b,c";
s.Split(',');

### Expected Behavior
Embeddinator with Visual Studio 2017 v15.8.x installed generates an AAR file.

### Actual Behavior
Embeddinator with Visual Studio 2017 v15.9.x installed gives the below error:

Linking assemblies...
 Mono.Cecil.ResolutionException: Failed to resolve System.String[] System.String::Split(System.Char,System.StringSplitOptions)

Modify all source for the String methods to pass in Char[] instead of Char will resolve the issue:
String s = "a,b,c";
s.Split(new char[] { ',' });

There are hundreds of places in my code which this modification would need to be applied and prefer not to risk such a widespread change.

### Environment
Embeddinator 0.4, VS2017 15.9.0, Windows 10 64 bit

```
Embeddinator-4000 v0.1 (0.4: 7664197)
```

### Build Logs

Embeddinator-4000.exe" --gen=Java --platform=Android -c -o output XXX.dll
Parsing assemblies...
    ...
Processing assemblies...
Generating binding code...
    Generated: ...
    ...
Compiling binding code...
Parsing assemblies...
    Parsed 'xxx.dll'
    Parsed 'xxx.dll'
Processing assemblies...
Generating binding code...
    Generated: xxx\Native_xxx.java
    Generated: mscorlib\system\IDisposableImpl.java
    Generated: mscorlib\system\IDisposable.java
    Generated: mscorlib\Native_mscorlib.java
    Generating Java stubs...
        D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\GenerateJavaStubs.proj(17,5): warning : Failed to read 'D:\EmbeddinatorTestFromVS2017_v15.9\Debug\xxx.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\GenerateJavaStubs.proj(17,5): warning : System.IO.FileNotFoundException: No symbol found for file: D:\EmbeddinatorTestFromVS2017_v15.9\Debug\xxx.dll
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\GenerateJavaStubs.proj(17,5): warning :    at Mono.Cecil.Cil.DefaultSymbolReaderProvider.GetSymbolReader(ModuleDefinition module, String fileName)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\GenerateJavaStubs.proj(17,5): warning :    at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\GenerateJavaStubs.proj(17,5): warning :    at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\GenerateJavaStubs.proj(17,5): warning :    at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\GenerateJavaStubs.proj(17,5): warning :    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\GenerateJavaStubs.proj(17,5): warning : Failed to read 'D:\EmbeddinatorTestFromVS2017_v15.9\Debug\xxx.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\GenerateJavaStubs.proj(17,5): warning : System.IO.FileNotFoundException: No symbol found for file: D:\EmbeddinatorTestFromVS2017_v15.9\Debug\xxx.dll
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\GenerateJavaStubs.proj(17,5): warning :    at Mono.Cecil.Cil.DefaultSymbolReaderProvider.GetSymbolReader(ModuleDefinition module, String fileName)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\GenerateJavaStubs.proj(17,5): warning :    at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\GenerateJavaStubs.proj(17,5): warning :    at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\GenerateJavaStubs.proj(17,5): warning :    at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\GenerateJavaStubs.proj(17,5): warning :    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\GenerateJavaStubs.proj(17,5): warning : Failed to read 'D:\EmbeddinatorTestFromVS2017_v15.9\Debug\xxx.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\GenerateJavaStubs.proj(17,5): warning : System.IO.FileNotFoundException: No symbol found for file: D:\EmbeddinatorTestFromVS2017_v15.9\Debug\xx.dll
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\GenerateJavaStubs.proj(17,5): warning :    at Mono.Cecil.Cil.DefaultSymbolReaderProvider.GetSymbolReader(ModuleDefinition module, String fileName)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\GenerateJavaStubs.proj(17,5): warning :    at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\GenerateJavaStubs.proj(17,5): warning :    at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\GenerateJavaStubs.proj(17,5): warning :    at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\GenerateJavaStubs.proj(17,5): warning :    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file)

Compiling binding code...
        Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

    Linking assemblies...
        D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\Package.proj(17,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly.
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\Package.proj(17,5): error MSB4018: Mono.Linker.MarkException: Error processing method: 'xxx.IMessageSelector xxx.MessageSelector/<>c::<Parse>b__0_0(System.String)' in assembly: 'xxx.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.String[] System.String::Split(System.Char,System.StringSplitOptions)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\Package.proj(17,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\Package.proj(17,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\Package.proj(17,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\Package.proj(17,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\Package.proj(17,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\Package.proj(17,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.ProcessQueue()
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\Package.proj(17,5): error MSB4018:    --- End of inner exception stack trace ---
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\Package.proj(17,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.ProcessQueue()
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\Package.proj(17,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.Process()
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\Package.proj(17,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\Package.proj(17,5): error MSB4018:    at Mono.Linker.Pipeline.Process(LinkContext context)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\Package.proj(17,5): error MSB4018:    at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\Package.proj(17,5): error MSB4018:    at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\Package.proj(17,5): error MSB4018:    at Xamarin.Android.Tasks.LinkAssemblies.Execute()
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\Package.proj(17,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
D:\EmbeddinatorTestFromVS2017_v15.9\Debug\output\Package.proj(17,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

Failed to compile generated code.

**Comment by nisewond** [comment]
All of the methods which are failing are declared as taking an argument of type: params char[]
Compling the DLLs with VS2017 v15.8.x succeeds with the embeddinator link step.  Compling the DLLs with VS2017 v15.9.x fails.

**Comment by galilov** [comment]
Is there any workaround? I faced the same issue :(

**Comment by Kazark** [comment]
We've hit the same issue as well.

**Comment by mercury233** [comment]
> I copied
`C:\Program Files (x86)\Mono\lib\mono\4.5\mscorlib.dll`
or
`C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\mscorlib.dll`
to replace
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\mscorlib.dll`
and it seems work

https://github.com/mercury233/libWindbot/commit/4dc883b50c55f485ebdc56ebc73858ba42011719
replace the old dll and it work for me
